name: HI

on:
  pull_request: 
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup complete"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: echo "Build complete"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploy complete"

  call-tests:
    uses: ./.github/workflows/called.yml
    needs: deploy
    with:
      env_name: "production"
