name: Run Tests

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Setup
        run: echo "Setting up in ${{ inputs.env_name }}"

      - name: Step 2 Run tests
        run: echo "Running tests"

      - name: Step 3 Analyze results
        run: echo "Analyzing results"

  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Setup
        run: echo "Setting up in ${{ inputs.env_name }}"

      - name: Step 2 Run tests
        run: echo "Running tests"

      - name: Step 3 Analyze results
        run: echo "Analyzing results"
  test-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Setup
        run: echo "Setting up in ${{ inputs.env_name }}"

      - name: Step 2 Run tests
        run: echo "Running tests"

      - name: Step 3 Analyze results
        run: echo "Analyzing results"
  call-bests:
    uses: ./.github/workflows/called2.yml
    needs: deploy
    with:
      env_name: "bests"
