name: Run Tests

on:
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2 Run tests
        run: echo "Running tests"

      - name: Step 3 Analyze results
        run: echo "Analyzing results"

