name: Dynamic Matrix Example

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          matrix=$(cat <<EOF
          [
            {"job-name": "job 1", "execute": "echo \"hello\""},
            {"job-name": "job2 2", "execute": "echo \"bye\""}
          ]
          EOF
          )
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  template-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    name: ${{ matrix.job-name }}
    steps:
      - run: ${{ matrix.execute }}
