name: Dynamic Matrix Example

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        shell: bash
        run: |
          matrix="[{\"job-name\": \"job 1\", \"execute\": \"echo \\\"hello\\\"\"}, {\"job-name\": \"job 2\", \"execute\": \"echo \\\"bye\\\"\"}]"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  template-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    name: ${{ matrix.job-name }}
    steps:
      - run: ${{ matrix.execute }}
