name: A

on:
  workflow_dispatch:
    inputs:
      count:
        type: number
        required: true
        default: 3

  workflow_call:
    inputs:
      count:
        type: number
        required: true

jobs:
  call-b:
    uses: ./.github/workflows/workflow-b.yml
    with:
      count: ${{ inputs.count }}
